config/routes.rb
Rails.application.routes.draw do

  resources :shops
  resources :upload_files
  resources :list_blancas
  resources :historics

  get 'home/index'
  get 'ptlfs/filtro'
  get 'clients/show_client'
  get 'clients/dynamic'
  get 'cards/send_file'

  get 'message/index'
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :bins
  resources :banks
  resources :switches
  resources :clients
  resources :card_types
  resources :cards
  resources :districts
  resources :regions
  resources :currencies
  resources :bins
  resources :partial_transacctions
  resources :transacction_types
  resources :ptlfs
  resources :plans
  resources :promotions
  resources :affiliations
  resources :affiliate_promotions
  resources :routers
  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/bin.rb
class Bin < ActiveRecord::Base

  has_many :promotions
  belongs_to :cardType

end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  before_action :set_bin, only: [:show, :edit, :update, :destroy]

  # GET /bins
  # GET /bins.json
  def index
    @bins = Bin.all
  end

  # GET /bins/1
  # GET /bins/1.json
  def show
  end

  # GET /bins/new
  def new
    @bin = Bin.new
  end

  # GET /bins/1/edit
  def edit
  end

  # POST /bins
  # POST /bins.json
  def create
    @bin = Bin.new(bin_params)

    respond_to do |format|
      if @bin.save
        format.html { redirect_to @bin, notice: 'Bin was successfully created.' }
        format.json { render :show, status: :created, location: @bin }
      else
        format.html { render :new }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bins/1
  # PATCH/PUT /bins/1.json
  def update
    respond_to do |format|
      if @bin.update(bin_params)
        format.html { redirect_to @bin, notice: 'Bin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bin }
      else
        format.html { render :edit }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bins/1
  # DELETE /bins/1.json
  def destroy
    @bin.destroy
    respond_to do |format|
      format.html { redirect_to bins_url, notice: 'Bin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bin
      @bin = Bin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bin_params
      params.require(:bin).permit(:number, :fiid, :count, :amount)
    end
end

app/helpers/bins_helper.rb
module BinsHelper
end

app/views/bins/_form.html.erb
<%= form_for(@bin) do |f| %>
  <% if @bin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bin.errors.count, "error") %> prohibited this bin from being saved:</h2>

      <ul>
      <% @bin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <form role="form">
      <h3 class="block-title">Configuration</h3>
      <br>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.number_field :name, class: "form-control col-lg-3", placeholder: "Enter the bin cards number" %>
      </div>
      <div class="field">
        <%= f.label :fiid %><br>
        <%= f.text_field :fiid, class: "form-control col-lg-3", placeholder: "Enter the FIID name" %>
      </div>
      <h3 class="block-title">Stand in</h3>
      <br>
      <div class="field">
        <%= f.label :count %><br>
        <%= f.number_field :count, class: "form-control col-lg-3", placeholder: "Enter the number transacction per day" %>
      </div>
      <div class="field">
        <%= f.label :amount %><br>
        <%= f.number_field :amount, class: "input-sm form-control mask-money", placeholder: "Enter the amount per day", maxlength: "22", autocomplete: "off"%>
      </div>
      <div class="actions">

        <%= f.submit :class => "btn btn-sm m-t-10" %>
        <%= link_to 'Back', bins_path , :class => "btn btn-sm m-t-10"%>
        <%= link_to 'Show', @bin , :class => "btn btn-sm m-t-10"%>


      </div>
    </form>
  </div>
<% end %>

app/views/bins/edit.html.erb
  <h1>Editing Bin</h1>

  <%= render 'form' %>

  <%#= link_to 'Back', bins_path , :class => "btn btn-sm m-t-10"%>

app/views/bins/index.html.erb
<div class="block-area" id="responsiveTable">

<h1>Listing Bins</h1>

  <div class="table-responsive overflow" tabindex="5005" style="overflow: hidden; outline: none;">
    <table class="tile table table-bordered table-striped">
      <thead>
      <tr>
        <th>Number</th>
        <th>Fiid</th>
        <th>Count</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @bins.each do |bin| %>
          <tr>
            <td><%= bin.number %></td>
            <td><%= bin.fiid %></td>
            <td><%= bin.count %></td>
            <td><%= bin.amount %></td>
            <td><%= link_to 'Show', bin %></td>
            <td><%= link_to 'Edit', edit_bin_path(bin) %></td>
            <td><%= link_to 'Destroy', bin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <br>

  <%= link_to 'New Bin', new_bin_path , :class => "btn btn-sm m-t-10"%>

</div>

app/views/bins/new.html.erb
  <h1>New Bin</h1>

  <%= render 'form' %>

app/views/bins/show.html.erb
  <p>
    <strong>Number:</strong>
    <%= @bin.number %>
  </p>

  <p>
    <strong>Fiid:</strong>
    <%= @bin.fiid %>
  </p>

  <p>
    <strong>Count:</strong>
    <%= @bin.count %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @bin.amount %>
  </p>

  <%= link_to 'Edit', edit_bin_path(@bin),:class => "btn btn-sm m-t-10" %> |
  <%= link_to 'Back', bins_path, :class => "btn btn-sm m-t-10" %>