config/routes.rb
Rails.application.routes.draw do

  resources :shops
  resources :upload_files
  resources :list_blancas
  resources :historics

  get 'home/index'
  get 'ptlfs/filtro'
  get 'clients/show_client'
  get 'clients/dynamic'
  get 'cards/send_file'

  get 'message/index'
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :bins
  resources :banks
  resources :switches
  resources :clients
  resources :card_types
  resources :cards
  resources :districts
  resources :regions
  resources :currencies
  resources :bins
  resources :partial_transacctions
  resources :transacction_types
  resources :ptlfs
  resources :plans
  resources :promotions
  resources :affiliations
  resources :affiliate_promotions
  resources :routers
  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :port, :contract)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :contract %><br>
    <%= f.text_field :contract %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing Shops</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Port</th>
      <th>Contract</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.port %></td>
        <td><%= shop.contract %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Port:</strong>
  <%= @shop.port %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @shop.contract %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>