config/routes.rb
Rails.application.routes.draw do

  resources :shops
  resources :upload_files
  resources :list_blancas
  resources :historics

  get 'home/index'
  get 'ptlfs/filtro'
  get 'clients/show_client'
  get 'clients/dynamic'
  get 'cards/send_file'

  get 'message/index'
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :bins
  resources :banks
  resources :switches
  resources :clients
  resources :card_types
  resources :cards
  resources :districts
  resources :regions
  resources :currencies
  resources :bins
  resources :partial_transacctions
  resources :transacction_types
  resources :ptlfs
  resources :plans
  resources :promotions
  resources :affiliations
  resources :affiliate_promotions
  resources :routers
  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/historic.rb
class Historic < ApplicationRecord
end

app/controllers/historics_controller.rb
class HistoricsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_historic, only: [:show, :edit, :update, :destroy]
  before_action :auth, :permisos_vistas, :horarios
  require 'time'
  # GET /historics
  # GET /historics.json
  def index
    if @permisos[2] == 2
      if params[:search].present? || params[:historic].present? || params[:start].present? || params[:end].present?
        @consulta = ""
        @busqueda = ""
        @registro = ""
        if params[:search].present?
          @busqueda = params[:search].gsub(/[^a-zA-Z0-9 ]/, '');
          @consulta = @consulta + "user_name LIKE '%#{@busqueda}%'"
          @registro = @registro + "User: #{@busqueda}"
        end
        if params[:historic][:action].present?
          @consulta = @consulta + " AND" if @consulta.present?
          @consulta = @consulta + " action = '#{params[:historic][:action]}'"
          @registro = @registro + " Action: #{params[:historic][:page]}"
        end
        if params[:start].present?
          @consulta = @consulta + " AND" if @consulta.present?
          @consulta = @consulta + " date >= '#{params[:start].to_date.strftime("%Y-%m-%d")}'"
          @registro = @registro + " Start date: #{params[:start]}"
        end
        if params[:end].present?
          @consulta = @consulta + " AND" if @consulta.present?
          @consulta = @consulta + " date <= '#{params[:end].to_date.strftime("%Y-%m-%d")}'"
          @registro = @registro + " End date: #{params[:end]}"
        end
        if params[:historic][:page].present?
          @consulta = @consulta + " AND" if @consulta.present?
          @consulta = @consulta + " page = '#{params[:historic][:page]}'"
          @registro = @registro + " Page: #{params[:historic][:page]}"
        end
        registro(3, @registro)
        puts "Query #{@consulta}"
        @historics = Historic.where("#{@consulta}").page(params[:page]).order(date: :desc).per(10)
        @error = 1 if @historics.empty?
      else
        @historics = Historic.all.page(params[:page]).order(date: :desc).per(10)
      end
    else
      redirect_to message_path, :alert => t('all.not_access')
    end
  end


  def show
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  def new
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  def edit
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  def create
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  def update
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  def destroy
    redirect_to no_permission_index_path, :alert => t('all.not_access')
  end

  private

  def registro(accion, detalle)
    @historic = Historic.new
    @historic.page = "Binnacle"
    @historic.user_name = current_user.name + " " + current_user.last_name
    @historic.user_id = current_user.id
    @historic.action = accion
    @historic.date = Time.now()
    @historic.detail = detalle.to_json
    @historic.save
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_historic
    @historic = Historic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def historic_params
    params.require(:historic).permit(:string, :string, :string, :interger, :string)
  end

  def permisos_vistas
    # se verifican los permisos de la vista y se almacenan
    consulta = Permission.where("view_id = 14 and profile_id = ?", current_user.profile_id)
    consulta.each do |permisos|
      @permisos = Array[permisos.crear, permisos.editar, permisos.leer, permisos.eliminar, permisos.horainicial, permisos.horafinal]
    end
  end

  def horarios
    unless Time.now >= Time.parse(@permisos[4].strftime("%H:%M")) && Time.now <= Time.parse(@permisos[5].strftime("%H:%M")) || @permisos[5].strftime("%H:%M") == "00:00" || @permisos[4].strftime("%H:%M") == "00:00"
      redirect_to message_index_path, :alert => t('all.not_access');
    end
  end

  def auth
    unless current_user && current_user.habilitado != 0 && current_user.activo != 0 then
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end
end

app/views/historics/_form.html.erb
<%= form_for(historic) do |f| %>
  <% if historic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historic.errors.count, "error") %> prohibited this historic from being saved:</h2>

      <ul>
      <% historic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :interger %>
    <%= f.text_field :interger %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/historics/_histori.html.erb
<%# <%********************* Sweetalert No Results *************************** %>
<% if @error.present? %>
  <script>
      swal({title: "<%= t('all.no_filter')%>", type: "error"});
  </script>
<% end %>
<%# <%*********************** Mostrar Busqueda actual *******************************%>
<% if @busqueda.present? %>
  <div class="row">
    <div class="col-md-1">
      <%= link_to t('all.clean'), historics_path, :class => 'btn btn-sm btn-primary dim' %>
    </div>
    <!-- <div class="col-md-11">
      <h3><%= t('all.query') %>: <%= @busqueda %></h3>
    </div> -->
  </div>
<% end %>
<%# <%**************************** Paginacion **************************************%>
<div align="right">
  <%= page_entries_info @historics, entry_name: t('views.historics_index.kami') %>
</div>
<div class="pag_right" align="right">
  <%= paginate @historics, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
</div>
<%# <%********************** Tabla Areas *******************************%>
<div id="tabla_areas" style="overflow: auto;">
  <table class="table footable no-paging">
    <thead>
    <tr>
      <th class="text-left" data-sort-ignore="true" data-hide="phone, tablet"><%= t('views.historics_index.page') %></th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone, tablet"><%= t('views.historics_index.action') %></th>
      <th class="text-center" data-sort-ignore="true"><%= t('views.historics_index.username') %></th>
      <th class="text-center" data-sort-ignore="true" data-hide="all"><%= t('views.historics_index.detail') %></th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone, tablet"><%= t('views.historics_index.date') %></th>
    </tr>
    </thead>

    <tbody>
    <% @historics.each do |historic| %>
      <tr>
        <td class="text-left"><%= t("views.profiles_show.#{historic.page}") %></td>
        <td class="text-center">
          <% case historic.action
             when '1' %><%= t('views.historics_index.create') %>
            <% when '2' %><%= t('views.historics_index.edit') %>
            <% when '3' %><%= t('views.historics_index.index') %>
            <% when '4' %><%= t('views.historics_index.destroy') %>
            <% when '5' %><%= t('views.historics_index.show') %>
          <% end %>
        </td>
        <td class="text-center"><%= historic.user_name %></td>
        <td class="text-center"><%= historic.detail %></td>
        <td class="text-center"><%= historic.date %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<%# <%**************************** Paginacion **************************************%>
<div align="right">
  <%= page_entries_info @historics, entry_name: t('views.historics_index.kami') %>
</div>
<div class="pag_right" align="right">
  <%= paginate @historics, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
</div>

<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>
<script>
    $('table').footable({paginate: false});
</script>

app/views/historics/edit.html.erb
<h1>Editing Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Show', @historic %> |
<%= link_to 'Back', historics_path %>

app/views/historics/index.html.erb
<div class="row">
  <div class="animated fadeInRight col-xs-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.historicos') %></h1>
        <div class="panel ibox-content">
<%# <%****************************** Body *********************************** %>
<%# <%*********************** Barra de busqueda *******************************%>
          <%= form_tag({:controller => "historics", :action => "index"}, :method => "get", :id => "binsearch") do %>
            <div class="row">
              <div class="col-xs-12 col-md-offset-2 col-md-8 form-group">
                <input type="search" class="form-control" name="search" autocomplete="off" id="areaserach" placeholder="<%= t('views.historics_index.place_name') %>">
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-offset-2 col-md-4 form-group">
                <select class="form-control" id="accion" name="historic[page]">
                  <option value=""> <%= t('views.historics_index.select_page') %> </option>
                  <% @views = View.all %>
                  <% @views.each do |p| %>
                    <option value="<%= p.name %>"> <%= t("views.profiles_show.#{p.name}") %> </option>
                  <% end %>
                </select>
              </div>
              <div class="col-xs-12 col-md-4 form-group">
                <select class="form-control" id="accion" name="historic[action]">
                  <option value=""> <%= t('views.historics_index.select_action') %> </option>
                  <option value="1"><%= t('views.historics_index.create') %></option>
                  <option value="2"><%= t('views.historics_index.edit') %></option>
                  <option value="3"><%= t('views.historics_index.index') %></option>
                  <option value="4"><%= t('views.historics_index.destroy') %></option>
                  <option value="5"><%= t('views.historics_index.show') %></option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-offset-2 col-md-4 col-xs-12">
                <div class="input-group date" id="start">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  <input name="start" class="form-control" placeholder="<%= t('all.placeholder_fecha') %>" autocomplete="off" id="str" >
                </div>
              </div>
              <div class="form-group col-md-4 col-xs-12">
                <div class="input-group date" id="end">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  <input name="end" class="form-control" placeholder="<%= t('all.placeholder_fecha') %>" autocomplete="off" id="end" >
                </div>
              </div>
            </div>

            <div class="text-center">
              <%= button_tag(type: 'submit', class: 'btn btn-primary', id: "btnrt") do %>
                <i class="fa fa-search"></i> <%= t('all.btn_search') %>
              <% end %>
            </div>


          <% end %>
          <div id="histori"><%= render 'histori' %></div>
<%# <%****************************** Body *********************************** %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnrt").click(function () {
            $.get($("#binsearch").attr("action"), $("#binsearch").serialize(), null, "script");
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        let end = $("#end"),
            dats = $('#start'),
            date = $('#end'),
            str = $('#str'),
            idioma_app = $('#idioma_app').val();

        //********************** Data Mask ***************************
        str.mask("99/99/9999");
        end.mask("99/99/9999");

        //********************** Date Picker *************************
        dats.datepicker({
            format: 'dd/mm/yyyy',
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            language: `${idioma_app}`,
            autoclose: true,
            endDate: '+0d'
        });
        date.datepicker({
            format: 'dd/mm/yyyy',
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            language: `${idioma_app}`,
            autoclose: true,
            endDate: '+0d'
        });
        //Script para los datepicker//
        // $('#rule_initial_date, #rule_end_date').on('input', function () {
        //     valor = $(this).val()
        //     patron = /^[0-9/]*$/
        //     remp = /[^ 0-9/]+/gi
        //
        //     if (!patron.test(valor)) {
        //         this.value = valor.replace(remp, "");
        //     }
        // });
        var getDate = function (input) {
            return new Date(input.date.valueOf());
        }
        // $('.entrada, .salida').datepicker({
        //     format: "yyyy-mm-dd",
        //     language: 'es',
        //     todayBtn: "linked",
        //     autoclose: true,
        //     calendarWeeks: true,
        // });
        date.datepicker({
            startDate: '+6d',
            endDate: '+0d',
        }).on('changeDate',
            function (selected) {
                dats.datepicker('clearDates');
                dats.datepicker('setEndDate', getDate(selected));
            });
        dats.datepicker({
            startDate: '+5d',
            endDate: '+0d',
        }).on('changeDate',
            function (selected) {
                date.datepicker('clearDates');
                date.datepicker('setStartDate', getDate(selected));
            });
        //Script para los datepicker//
    });
</script>

app/views/historics/index.js.erb
$("#histori").html("<%= escape_javascript(render("histori")) %>");
$('table').footable({paginate: false});

app/views/historics/new.html.erb
<h1>New Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Back', historics_path %>

app/views/historics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @historic.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @historic.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @historic.string %>
</p>

<p>
  <strong>Interger:</strong>
  <%= @historic.interger %>
</p>

<p>
  <strong>String:</strong>
  <%= @historic.string %>
</p>

<%= link_to 'Edit', edit_historic_path(@historic) %> |
<%= link_to 'Back', historics_path %>