config/routes.rb
Rails.application.routes.draw do

  resources :shops
  resources :upload_files
  resources :list_blancas
  resources :historics

  get 'home/index'
  get 'ptlfs/filtro'
  get 'clients/show_client'
  get 'clients/dynamic'
  get 'cards/send_file'

  get 'message/index'
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :bins
  resources :banks
  resources :switches
  resources :clients
  resources :card_types
  resources :cards
  resources :districts
  resources :regions
  resources :currencies
  resources :bins
  resources :partial_transacctions
  resources :transacction_types
  resources :ptlfs
  resources :plans
  resources :promotions
  resources :affiliations
  resources :affiliate_promotions
  resources :routers
  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base

  has_many :affiliatePromotions
  belongs_to :district
  belongs_to :region

end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_affiliation, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  @@store = "Shops"

  def index
    begin
      if current_user
        @cu = current_user.profile_id
        if @cu != 0
          @per = Permission.where("view_name = 'Shops' and profile_id = ?", @cu)
          @per.each do |permisos|
            @uno = permisos.view_name
            @crearStore = permisos.crear
            @editarStore = permisos.editar
            @leerStore = permisos.leer
            @eliminarStore = permisos.eliminar
            if @uno == @@store
              @@crear = permisos.crear
              @@editar = permisos.editar
              @@leer = permisos.leer
              @@eliminar = permisos.eliminar

              @crear = permisos.crear
              @editar = permisos.editar
              @leer = permisos.leer
              @eliminar = permisos.eliminar
            end
          end
          if ((@@leer == 2) || (@@crear == 8) || (@@editar == 4) || (@@eliminar == 1))
            if params[:search].present?
              registro(3, params[:search]);
              busqueda = params[:search].strip
              if Affiliation.where("name like '%#{busqueda}%'").present?
                @affiliations = Affiliation.where("name like '%#{busqueda}%'").order("created_at DESC").page(params[:page]).per(20)
                @query = busqueda
              elsif Affiliation.where("address like '%#{busqueda}%'").present?
                @affiliations = Affiliation.where("address like '%#{busqueda}%'").order("created_at DESC").page(params[:page]).per(20)
                @query = busqueda
              elsif Region.where("name like '%#{busqueda}%'").present?
                @regi = Region.where("name like '%#{busqueda}%'")
                @regi.each do |region|
                  @affiliations = Affiliation.where("region_id = ?", region.id).order("created_at DESC").page(params[:page]).per(20)
                  @query = busqueda
                end
              elsif District.where("name like '%#{busqueda}%'").present?
                @distric = District.where("name like '%#{busqueda}%'")
                @distric.each do |dist|
                  @affiliations = Affiliation.where("district_id = ?", dist.id).order("created_at DESC").page(params[:page]).per(20)
                  @query = busqueda
                end
              else
                @affiliations = Affiliation.order("created_at DESC").page(params[:page]).per(20)
                @error = true
              end
            else
              @affiliations = Affiliation.order("created_at DESC").page(params[:page]).per(20)
            end
          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_access')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    rescue => e
      logger = Logger.new('log/erroraffiliations.log')
      logger.error("Error affiliations en el metodo index #{Time.now.to_s}")
      logger.error(e)
      @metod = "affiliations método index"
      file = "#{Rails.root}/app/views/errors/file.txt"
      File.open(file, 'w') {|file| file.write("#{e.backtrace}")}
      @error = "#{e.message }"
      file_send
      if e.message == "ActionController::UnknownFormat"
        render_404
      else
        render_500
      end
    end
  end

  def show
    begin
      if current_user
        @cu = current_user.profile_id
        if @cu != 0
          @per = Permission.where("view_name = 'Shops' and profile_id = ?", @cu)
          @per.each do |permisos|
            @uno = permisos.view_name
            @leerStore = permisos.leer
            if @uno == @@store
              @@leer = permisos.leer

              @leer = permisos.leer
            end
          end
          if (@@leer == 2)
            registro(5, @affiliation);
          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_access')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    rescue => e
      logger = Logger.new('log/erroraffiliations.log')
      logger.error("Error affiliations en el metodo show #{Time.now.to_s}")
      logger.error(e)
      @metod = "affiliations método show"
      file = "#{Rails.root}/app/views/errors/file.txt"
      File.open(file, 'w') {|file| file.write("#{e.backtrace}")}
      @error = "#{e.message }"
      file_send
      if e.message == "ActionController::UnknownFormat"
        render_404
      else
        render_500
      end
    end
  end

  def new
    begin
      if current_user
        @cu = current_user.profile_id
        if @cu != 0
          @per = Permission.where("view_name = 'Shops' and profile_id = ?", @cu)
          @per.each do |permisos|
            @uno = permisos.view_name
            @crearStore = permisos.crear
            if @uno == @@store
              @@crear = permisos.crear

              @crear = permisos.crear
            end
          end
          if (@@crear == 8)
            @affiliation = Affiliation.new
          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_access')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    rescue => e
      logger = Logger.new('log/erroraffiliations.log')
      logger.error("Error affiliations en el metodo new #{Time.now.to_s}")
      logger.error(e)
      @metod = "affiliations método new"
      file = "#{Rails.root}/app/views/errors/file.txt"
      File.open(file, 'w') {|file| file.write("#{e.backtrace}")}
      @error = "#{e.message }"
      file_send
      if e.message == "ActionController::UnknownFormat"
        render_404
      else
        render_500
      end
    end
  end

  def edit
    begin
      if current_user
        @cu = current_user.profile_id
        if @cu != 0
          @per = Permission.where("view_name = 'Shops' and profile_id = ?", @cu)
          @per.each do |permisos|
            @uno = permisos.view_name
            @editarStore = permisos.editar
            if @uno == @@store
              @@editar = permisos.editar

              @editar = permisos.editar
            end
          end
          if (@@editar == 4)

          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_access')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    rescue => e
      logger = Logger.new('log/erroraffiliations.log')
      logger.error("Error affiliations en el metodo edit #{Time.now.to_s}")
      logger.error(e)
      @metod = "affiliations método edit"
      file = "#{Rails.root}/app/views/errors/file.txt"
      File.open(file, 'w') {|file| file.write("#{e.backtrace}")}
      @error = "#{e.message }"
      file_send
      if e.message == "ActionController::UnknownFormat"
        render_404
      else
        render_500
      end
    end
  end

  def create
    begin
      registro(1, @affiliation);
      @affiliation = Affiliation.new(affiliation_params)
      respond_to do |format|
        if Affiliation.where("name like ?", @affiliation.name).exists?
          format.html {
            @error2 = true
            render action: :new
          }
        else
          if @affiliation.save
            format.html {redirect_to :controller => 'affiliations', :action => 'index'}
            flash[:notice] = t('views.message_affi.new_affi')
            format.json {render :show, status: :created, location: @affiliation}
          else
            format.html {render :new}
            format.json {render json: @affiliation.errors, status: :unprocessable_entity}
          end
        end
      end
    rescue => e
      logger = Logger.new('log/erroraffiliations.log')
      logger.error("Error affiliations en el metodo create #{Time.now.to_s}")
      logger.error(e)
      @metod = "affiliations método create"
      file = "#{Rails.root}/app/views/errors/file.txt"
      File.open(file, 'w') {|file| file.write("#{e.backtrace}")}
      @error = "#{e.message }"
      file_send
      if e.message == "ActionController::UnknownFormat"
        render_404
      else
        render_500
      end
    end
  end

  def update
    begin
      registro(2, @affiliation)
      respond_to do |format|
        @consulta = Affiliation.find_by_name(params[:affiliation][:name])
        if @consulta.nil? || @consulta.id == @affiliation.id
          if @affiliation.update(affiliation_params)
            format.html {redirect_to :controller => 'affiliations', :action => 'index'}
            flash[:notice] = t('views.message_affi.edit')
            format.json {render :show, status: :created, location: @affiliation}
          else
            format.html {render :edit}

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_form.html.erb
<%= form_for @affiliation, :html => {:id => "form1", :role => "form"} do |f| %>
  <% if @affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@affiliation.errors.count, "error") %> prohibited this router from being saved:</h2>
      <ul>
        <% @affiliation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <%= button_tag(type: "submit", name: "commit", id: 'btnaffi1', :class => "btn btn-xs btn-primary", :data => {:no_turbolink => true}) do %>
        <i class="fa fa-floppy-o"></i> <%= t('views.affi_form.btn_save') %>
      <% end %>
      <%= link_to ('<i class="fa fa-industry"></i> ').html_safe + t('views.cards_form.btn_Back'), affiliations_path, :class => "btn btn-xs btn-danger", :data => {:no_turbolink => false} %>
    </div>
  </div>
  <br>
  <br>

  <div class="row">
    <div class="col-md-4 form-group" style="margin-top: 11px"s>
      <label class="required"><%= t('views.affi_index.name') %></label>
      <%= f.text_field :name, id: 'name', class: "form-control input-sm", placeholder: t('views.affi_index.name'), :autocomplete => :off, :maxlength => 255 %>
      <h4><span class="label" id="namelabel"></span></h4>
    </div>
    <div class="col-md-4 form-group">
      <label class="required"><%= t('views.affi_index.number') %></label>
      <span class="badge badge-secondary blue-tooltip" style="margin-bottom: 16px" id="helpnumero" data-toggle="tooltip" title="<%= t('views.affi_index.help1') %>">?</span>
      <%= f.text_field :number, id: 'number', class: "form-control input-sm", placeholder: "#{t('views.affi_index.ejemplo')}'#{"1234"}'", :autocomplete => :off, :maxlength => 4 %>
      <h4><span class="label" id="numberlabel"></span></h4>
    </div>
    <div class="col-md-4 form-group" style="margin-top: 11px">
      <label class="required"><%= t('views.affi_index.address') %></label>
      <%= f.text_field :address, id: 'address', class: "form-control input-sm", placeholder: t('views.affi_index.address'), :autocomplete => :off, :maxlength => 255 %>
      <h4><span class="label" id="addresslabel"></span></h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 form-group">
      <label class="required"><%= t('views.affi_index.affiliation') %></label>
      <span class="badge badge-secondary blue-tooltip" style="margin-bottom: 16px" id="helptienda" data-toggle="tooltip" title="<%= t('views.affi_index.help2') %>">?</span>
      <%= f.text_field :affiliation_id, class: "form-control input-sm", :id => "affil", placeholder: "#{t('views.affi_index.ejemplo')}'#{"1234"}'", :autocomplete => :off, :maxlength => 4 %>
      <h4><span class="label" id="affilabel"></span></h4>
    </div>
    <div class="col-md-4 form-group" style="margin-top: 11px">
      <label class="required"><%= t('views.affi_index.district') %></label>
      <%= f.collection_select :district_id, District.order(:name), :id, :name, {:include_blank => t('views.affi_form.tradu03')}, {:class => "form-control input-sm", id: 'Dist'} %>
      <h4><span class="label" id="districtlabel"></span></h4>
    </div>
    <div class="col-md-4 form-group" style="margin-top: 11px">
      <label class="required"><%= t('views.affi_index.region') %></label>
      <%= f.collection_select :region_id, Region.order(:name), :id, :name, {:include_blank => t('views.affi_form.tradu04')}, {:class => "form-control input-sm", id: 'Reg' } %>
      <h4><span class="label" id="regionlabel"></span></h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 form-group">
      <label class="required"><%= t('views.affi_index.port') %></label>
      <span class="badge badge-secondary blue-tooltip" style="margin-bottom: 16px" id="helppuerto" data-toggle="tooltip" title="<%= t('views.affi_index.help3') %>">?</span>
      <%= f.text_field :port, class: "form-control input-sm", :id => "port", placeholder: "#{t('views.affi_index.ejemplo')}'#{"12345"}'", :autocomplete => :off, :maxlength => 5 %>
      <h4><span class="label" id="port1"></span></h4>
    </div>
    <div class="col-8"></div>
  </div>
  <br>
  <br>

  <div class="row">
    <div class="col-md-4">
      <%= button_tag(type: "submit", name: "commit", id: 'btnaffi2', :class => "btn btn-xs btn-primary", :data => {:no_turbolink => true}) do %>
        <i class="fa fa-floppy-o"></i> <%= t('views.affi_form.btn_save') %>
      <% end %>
      <%= link_to ('<i class="fa fa-industry"></i> ').html_safe + t('views.cards_form.btn_Back'), affiliations_path, :class => "btn btn-xs btn-danger", :data => {:no_turbolink => false} %>
    </div>
  </div>

<% end %>

<script type="text/javascript" charset="utf-8">
    <% if @error2 == true  %>
    swal({
            title: '<%= t('views.message_affi.notice_blackup') %>.',
            type: 'warning',
            confirm: 'OK'
        }
    );
    <% end %>
</script>

app/views/affiliations/_tiendas.html.erb
<% if @query.present? %>
  <div class="row">
    <div class="col-md-7">
      <h4><%= t('all.query') %>: <%= @query %></h4>
    </div>
  </div>
<% end %>
<!-- Paginacion -->
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-3"></div>
  <div class="col-md-5 text-right">
    <div style="margin-bottom: 2em;">
      <div class="pag_right">
        <% if @affiliations.count == 1 %>
          <%= page_entries_info @affiliations, entry_name: t('views.affi_index.affiliation') %>
        <% else %>
          <%= page_entries_info @affiliations, entry_name: t('views.affi_index.affiliation').pluralize(@affiliations.count) %>
        <% end %>
      </div>
      <div class="detall_left">
        <%= paginate @affiliations, params: {controller: 'affiliations', action: 'index'}, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm', remote: true %>
      </div>
    </div>
  </div>
</div>
<table class="table footable" data-show-toggle="false" data-expand-first="true" data-page="false">
  <thead>
  <tr>
    <th data-sort-ignore="true" data-visible="true" data-sort-ignore="true" class="text-left"><%= t('views.affi_index.name') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center"><%= t('views.affi_index.number') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center" data-sort-ignore="true"><%= t('views.affi_index.address') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center"><%= t('views.affi_index.affiliation') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center" data-sort-ignore="true"><%= t('views.affi_index.district') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center" data-sort-ignore="true"><%= t('views.affi_index.region') %></th>
    <th data-sort-ignore="true" data-hide="phone,tablet" class="text-center" data-sort-ignore="true"><%= t('views.affi_index.port') %></th>
    <th data-sort-ignore="true" data-hide="phone" class="text-center"> <%= t('all.show') %> </th>
    <th data-sort-ignore="true" data-hide="phone" class="text-center"><%= t('views.affi_index.edit') %></th>
    <th data-sort-ignore="true" class="text-center"><%= t('views.affi_index.destroy') %></th>
  </tr>
  </thead>
  <tbody>
  <% @affiliations.each do |affiliation| %>
    <tr>
      <td class="text-left">
        <% if affiliation.name.present? %>
          <%= affiliation.name %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.number.present? %>
          <%= affiliation.number %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.address.present? %>
          <%= affiliation.address %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.affiliation_id.present? %>
          <%= affiliation.affiliation_id %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.district.present? %>
          <% if affiliation.district.name.present? %>
            <%= affiliation.district.name %>
          <% end %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.region.present? %>
          <% if affiliation.region.name.present? %>
            <%= affiliation.region.name %>
          <% end %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class="text-center">
        <% if affiliation.port.present? %>
          <%= affiliation.port %>
        <% else %>
          N/A
        <% end %>
      </td>
      <td class='text-center'>
        <% if @leerStore == 2 %>
          <%= link_to "<button class='btn btn-primary btn-xs blue-tooltip tolshow' data-toggle='tooltip' type='button'><i class='fa fa-file-text'></i></button>".html_safe, affiliation %>
        <% end %>
      </td>
      <td class="text-center">
        <% if @editarStore == 4 %>
          <%= link_to "<button class='btn btn-warning btn-xs blue-tooltip toledit' data-toggle='tooltip' type='button'><i class='fa fa-pencil'></i></button>".html_safe, edit_affiliation_path(affiliation), :data => {:no_turbolink => false} %>
        <% end %>
      </td>
      <td class="text-center">
        <% if @eliminarStore == 1 %>
          <input type="hidden" value="<%= affiliation.name %>" id="affi<%= affiliation.id %>">
          <button class="btn btn-danger btn-xs eliminar blue-tooltip toldelete" data-toggle='tooltip' id="<%= affiliation.id %>">
            <i class="fa fa-trash-o"></i>
          </button>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<!-- Paginacion -->
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-3"></div>
  <div class="col-md-5 text-right">
    <div style="margin-bottom: 2em;">
      <div class="pag_right">
        <%= paginate @affiliations, params: {controller: 'affiliations', action: 'index'}, :theme => 'twitter-bootstrap-3', :pagination_class => 'pagination-sm', remote: true %>
      </div>
      <div class="detall_left">
        <% if @affiliations.count == 1 %>
          <%= page_entries_info @affiliations, entry_name: t('views.affi_index.affiliation') %>
        <% else %>
          <%= page_entries_info @affiliations, entry_name: t('views.affi_index.affiliation').pluralize %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    <% if @error == true  %>
    swal({
            title: '<%= t('all.no_filter') %>.',
            type: 'error',
            confirm: 'OK'
        }
    );
    <% end %>
    $('table').footable({});
    $('.tolshow').attr('title', '<%= t('views.affi_show.title') %>');
    $('.toledit').attr('title', '<%= t('views.affi_edit.title') %>');
    $('.toldelete').attr('title', '<%= t('views.affi_index.destroy2') %>');
    $('[data-toggle="tooltip"]').tooltip();
</script>
<!--<style>-->
<!--  .blue-tooltip + .tooltip > .tooltip-inner {-->
<!--    background-color: #003057;-->
<!--  }-->
<!--</style>-->

app/views/affiliations/edit.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1><%= t('views.affi_edit.title') %></h1>
        </div>
        <div class="ibox-content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/affiliations/index.js.erb
$("#ta_shops").html("<%= escape_javascript(render("tiendas")) %>");

app/views/affiliations/new.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1><%= t('views.affi_new.title') %></h1>
        </div>
        <div class="ibox-content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/affiliations/show.html.erb
<div class="block-area wrapper wrapper-content animated fadeInRight" id="responsiveTable">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h1><%= t('views.affi_show.title') %></h1>
          <div class="ibox-content">
            <div class="row">
              <div class="col-md-4">
                <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t('views.affi_index.btn_New'), new_affiliation_path, :class => "btn btn-primary btn-xs", :data => {:no_turbolink => true} %>
                <%= link_to ('<i class="fa fa-industry"></i> ').html_safe + t('all.back'), affiliations_path, :class => "btn btn-xs btn-warning", :data => {:no_turbolink => false} %>
              </div>
            </div>
            <br>
            <table class="table footable" data-show-toggle="false" data-expand-first="true" data-page-size="20">
              <thead>
              <tr>
                <th data-sort-ignore="true" class="text-center" data-visible="true"><%= t('views.affi_index.name') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone"><%= t('views.affi_index.number') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone,tablet"><%= t('views.affi_index.address') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone,tablet"><%= t('views.affi_index.affiliation') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone,tablet"><%= t('views.affi_index.district') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone,tablet"><%= t('views.affi_index.region') %></th>
                <th data-sort-ignore="true" class="text-center" data-hide="phone,tablet"><%= t('views.affi_index.port') %></th>
                <th data-sort-ignore="true" class="text-center"><%= t('views.affi_index.edit') %></th>
              </tr>
              </thead>
              <tbody>
              <td class="text-center">
                <% if @affiliation.name.present? %>
                  <%= @affiliation.name %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.number.present? %>
                  <%= @affiliation.number %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.address.present? %>
                  <%= @affiliation.address %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.affiliation_id.present? %>
                  <%= @affiliation.affiliation_id %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.district.present? %>
                  <%= @affiliation.district.name %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.region.present? %>
                  <%= @affiliation.region.name %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center">
                <% if @affiliation.port.present? %>
                  <%= @affiliation.port %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="text-center"
              ><%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil"></i></button>'.html_safe, edit_affiliation_path(@affiliation), :data => {:no_turbolink => false} %>
              </td>
              </tbody>
            </table>
            <br>
            <div class="row">
              <div class="col-md-4">
                <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t('views.affi_index.btn_New'), new_affiliation_path, :class => "btn btn-primary btn-xs", :data => {:no_turbolink => true} %>
                <%= link_to ('<i class="fa fa-industry"></i> ').html_safe + t('all.back'), affiliations_path, :class => "btn btn-xs btn-warning", :data => {:no_turbolink => false} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    $('table').footable({});
</script>